version: '3.8'
services:
  chat-app:
    build: ./chat-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
  backend:
    build: ./chat-server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatapp
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
