FROM node:20-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build the project
RUN npm run build  # Ensures compiled files are generated in `/dist`

# Run the compiled application
CMD ["node", "dist/src/index.js"]
